---
title: Робот Балакун
hero_image: images/chatbot.png
description: Ви навчитеся програмувати власного робота-співрозмовника!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: З днем народження
  - 
    title: Ваш чат-бот
  - 
    title: Чат-бот, що розмовляє
  - 
    title: "Challenge: більше питань"
    challenge: true
  - 
    title: Прийняття рішень
  - 
    title: "Challenge: більше рішень"
    challenge: true
  - 
    title: Зміна розташування
  - 
    title: "Challenge: завершення чат-боту"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
