---
title: Pratende Robot
hero_image: images/chatbot.png
description: Leer hoe je je eigen pratende robot kunt programmeren!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Inleiding
  - 
    title: Jouw chatbot
  - 
    title: Een pratende chatbot
  - 
    title: "Uitdaging: meer vragen"
    challenge: true
  - 
    title: Het nemen van beslissingen
  - 
    title: "Uitdaging: meer beslissingen"
    challenge: true
  - 
    title: Verander locatie
  - 
    title: "Uitdaging: maak je chatbot af"
    challenge: true
  - 
    title: Wat nu?
  - 
    title: What next?
