---
title: Pratende Robot
hero_image: images/chatbot.png
description: Leer hoe je je eigen pratende robot kunt programmeren!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Jouw chatbot
    completion:
      - engaged
  - 
    title: Een pratende chatbot
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
