---
title: Pratende Robot
hero_image: images/chatbot.png
description: Leer hoe je je eigen pratende robot kunt programmeren!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Jouw chatbot
  - 
    title: "Een pratende robot"
    challenge: true
  - 
    title: Het nemen van beslissingen
  - 
    title: "Locatie wijzigen"
    challenge: true
  - 
    title: 'Uitdaging: maak je chatbot af'
  - 
    title: "Uitdaging: maak je chatbot af"
    challenge: true
  - 
    title: Wat kun je verder nog doen?
