---
title: Chatbot
hero_image: images/chatbot.png
description: Learn how to program your own talking robot!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
- title: Introduction
- title: Your chatbot
  completion:
  - engaged
- title: A talking chatbot
  completion:
  - internal
- title: Making decisions
- title: Changing location
  completion:
  - external
- title: 'Challenge: finish your chatbot'
- title: What next?
