---
title: चॅटबॉट
hero_image: images/chatbot.png
description: 'आपल्या स्वत: च्या बोलणारा रोबोट कसे बनवायचे ते जाणून घ्या!'
theme: जांभळा
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: परिचय
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
    completion:
      - engaged
  - 
    title: 'Challenge: more questions'
    challenge: true
  - 
    title: निर्णय घेणे
  - 
    title: 'Challenge: more decisions'
    challenge: true
  - 
    title: Changing location
    completion:
      - internal
  - 
    title: 'Challenge: finish your chatbot'
    challenge: true
  - 
    title: What next?
