---
title: चॅटबॉट
hero_image: images/chatbot.png
description: 'आपल्या स्वत: च्या बोलणारा रोबोट कसे बनवायचे ते जाणून घ्या!'
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: जांभळा
duration: 0
listed: true
ingredient: false
copyedit: true
curriculum: १, डिझाइन-0, प्रोग्रामिंग-१, फेज- comp-0, उत्पादन-0, समुदाय-0
interests: ''
technology: scratch
site_areas: प्रकल्प
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: २०१७-०१-०१
steps:
  - 
    title: परिचय
  - 
    title: आपल्याला कशाची आवश्यकता लागेल
  - 
    title: आपले चॅटबॉट
  - 
    title: एक बोलत chatbot
  - 
    title: निर्णय घेणे
  - 
    title: स्थान बदलत आहे
  - 
    title: 'आव्हान: आपले चॅटबोट पूर्ण करा'
