---
title: चॅटबॉट
hero_image: images/chatbot.png
description: 'आपल्या स्वत: च्या बोलणारा रोबोट कसे बनवायचे ते जाणून घ्या!'
theme: जांभळा
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: परिचय
  - 
    title: आपला चॅटबोॉट
  - 
    title: बोलत चॅटबॉट
  - 
    title: "आव्हानः अधिक प्रश्न"
    challenge: true
  - 
    title: निर्णय घेणे
  - 
    title: "आव्हानः अधिक निर्णय"
    challenge: true
  - 
    title: बदलण्याचे स्थान
  - 
    title: "आव्हानः आपले चॅटबॉट समाप्त करा"
    challenge: true
  - 
    title: What next?
