---
title: Chatbot
hero_image: Изображения / chatbot.png
description: Узнайте, как программировать собственный робот-говорящий!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: Фиолетовый
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, production-0, community-0
interests: ''
technology: царапина
site_areas: проектов
technologies: царапина
hardware: ''
software: царапина
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Введение
  - 
    title: Что вам необходимо
  - 
    title: Ваш чатбот
  - 
    title: Говорящий чатбот
  - 
    title: Принимая решения
  - 
    title: Изменение местоположения
  - 
    title: 'Задача: завершить свой чатбот'
