---
title: Chatbot
hero_image: Изображения / chatbot.png
description: Узнайте, как программировать собственный робот-говорящий!
theme: Фиолетовый
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Введение
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Принимая решения
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
