---
title: चैटबॉट
hero_image: images/chatbot.png
description: अपने बोलने वाले रोबोट को प्रोग्राम करना सीखें!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
- title: परिचय
  completion: engaged
- title: आपका चैटबॉट
- title: बात करने वाला चैटबॉट
- title: 'चुनौती: अधिक प्रश्न'
  challenge: true
- title: निर्णय लेना
- title: 'चुनौती: अधिक निर्णय'
  challenge: true
  completion: internal
- title: स्थान बदलना
- title: 'चुनौती: अपना चैटबॉट समाप्त करना'
  challenge: true
- title: आगे क्या?
