---
title: चैटबॉट
hero_image: images/chatbot.png
description: अपने बोलने वाले रोबोट को प्रोग्राम करना सीखें!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
interests: social
technology: scratch
site_areas: codeclub, scratch
steps:
- title: भूमिका
- title: आपको किसकी ज़रूरत होगी
- title: आपका चैटबॉट
- title: बोलने वाला चैटबॉट
- title: निर्णय लेना
- title: स्थान बदलना
- title: ‘चुनौती: अपना चैटबॉट समाप्त करें’

