---
title: Робот који разговара
hero_image: images/chatbot.png
description: Научићете да програмирате сопственог робота који разговара!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Увод
  - 
    title: Твој робот који разговара
  - 
    title: Робот који разговара
  - 
    title: "Изазов: Више питања"
    challenge: true
  - 
    title: Доношење одлука
  - 
    title: "Изазов: Више одлука"
    challenge: true
  - 
    title: Промена локације
  - 
    title: "Изазов: Доврши свог робота"
    challenge: true
  - 
    title: Шта даље?
