---
title: Chatbot
hero_image: images/chatbot.png
description: Learn how to program your own talking robot!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: social
technology: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: Making decisions
  - 
    title: Changing location
  - 
    title: 'Challenge: finish your chatbot'

