---
title: Chatbot
hero_image: beelde / chatbot.png
description: Leer hoe om jou eie praatrobot te programmeer!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018/09/20
steps:
  - 
    title: inleiding
  - 
    title: Jou chatbot
  - 
    title: '''N Praatjie chatbot'
  - 
    title: "Uitdaging: meer vrae"
    challenge: true
  - 
    title: Besluite neem
  - 
    title: "Uitdaging: meer besluite"
    challenge: true
  - 
    title: Ligging verander
  - 
    title: "Uitdaging: voltooi jou chatbot"
    challenge: true
  - 
    title: Toets jouself
  - 
    title: Wat volgende?
