---
title: Chatbot
hero_image: images/chatbot.png
description: Tìm hiểu cách lập trình robot biết trò chuyện của riêng bạn!
theme: màu tím
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Giới thiệu
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Đưa ra quyết định
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
