---
title: Chatbot
hero_image: images/chatbot.png
description: Tìm hiểu cách lập trình robot biết trò chuyện của riêng bạn!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: màu tím
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: scratch
site_areas: dự án
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Chatbot của bạn
  - 
    title: Robot biết trò chuyện
  - 
    title: Đưa ra quyết định
  - 
    title: Thay đổi vị trí
  - 
    title: 'Thử thách: hoàn thành chatbot của bạn'
