---
title: Chatbot
hero_image: images/chatbot.png
description: Nu skal du lære hvordan du programmerer din egen talende robot!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Din chatbot
    completion:
      - engaged
  - 
    title: En snakende chatbot
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
