---
title: Chatbot
hero_image: images/chatbot.png
description: Nu skal du lære hvordan du programmerer din egen talende robot!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introduktion
  - 
    title: Din chatbot
  - 
    title: En snakende chatbot
    completion:
      - engaged
  - 
    title: 'Udfordring: flere spørgsmål'
    challenge: true
  - 
    title: Tage beslutninger
  - 
    title: 'Udfordring: flere beslutninger'
    challenge: true
  - 
    title: Ændring af placering
    completion:
      - internal
  - 
    title: 'Udfordring: Afslut din chatbot'
    challenge: true
  - 
    title: Hvad er næste skridt?
