---
title: chatbot
hero_image: images/chatbot.png
description: Nu skal du lære hvordan du programmerer din egen talende robot!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Tillykke Med Fødselsdagen
  - 
    title: Din chatbot
  - 
    title: En snakende chatbot
  - 
    title: "Udfordring: flere spørgsmål"
    challenge: true
  - 
    title: Tage beslutninger
  - 
    title: "Udfordring: flere beslutninger"
    challenge: true
  - 
    title: Ændring af placering
  - 
    title: "Udfordring: Afslut din chatbot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
