---
title: Robô Falante
hero_image: images/chatbot.png
description: Aprende a programar o teu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: O teu robô falante
    completion:
      - engaged
  - 
    title: Um robô falante
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
