---
title: Robot Falador
hero_image: images/chatbot.png
description: Vais aprender como programar o teu próprio robot que fala!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-09-20
steps:
  - 
    title: Robot Falador
  - 
    title: O teu robô falante
  - 
    title: Um robô falante
  - 
    title: "Desafio: mais perguntas"
    challenge: true
  - 
    title: Tomar decisões
  - 
    title: "Desafio: mais perguntas"
    challenge: true
  - 
    title: Mudar de localização
  - 
    title: "Desafio: termina o teu robô falante"
    challenge: true
  - 
    title: What next?
