---
title: Robô Falante
hero_image: images/chatbot.png
description: Aprende a programar o teu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introdução
  - 
    title: O teu robô falante
  - 
    title: Um robô falante
  - 
    title: "Desafio: mais perguntas"
    challenge: true
  - 
    title: Tomar decisões
  - 
    title: "Desafio: mais perguntas"
    challenge: true
  - 
    title: Alterar local
  - 
    title: "Desafio: termina o teu robô falante"
    challenge: true
  - 
    title: What next?
