---
title: Robot koji razgovara
hero_image: images/chatbot.png
description: U ovom projektu naučit ćeš programirati robota koji razgovara s korisnikom!
theme: ljubičasta
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Tvoj chatbot
    completion:
      - engaged
  - 
    title: Robot koji govori
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
