---
title: Robot koji razgovara
hero_image: images/chatbot.png
description: U ovom projektu naučit ćeš programirati robota koji razgovara s korisnikom!
theme: ljubičasta
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Tvoj chatbot
  - 
    title: Robot koji govori
  - 
    title: "Izazov: još pitanja"
    challenge: true
  - 
    title: Donošenje odluka
  - 
    title: "Izazov: više odluka"
    challenge: true
  - 
    title: Promjena lokacije
  - 
    title: "Izazov: dovrši robota"
    challenge: true
  - 
    title: What next?
