---
title: Robot koji razgovara
hero_image: images/chatbot.png
description: U ovom projektu naučit ćeš programirati robota koji razgovara s korisnikom!
theme: ljubičasta
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Donošenje odluka
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
