---
title: Juttelubotti
hero_image: images/chatbot.png
description: Opi ohjelmoimaan oma puhuva robottisi!
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Esittely
  - 
    title: Mitä tarvitset
  - 
    title: Juttelubottisi
  - 
    title: Puhuva juttelubotti
  - 
    title: Päätösten tekeminen
  - 
    title: Sijainnin muuttaminen
  - 
    title: 'Haaste: viimeistele juttelubottisi'
