---
title: Juttelubotti
hero_image: images/chatbot.png
description: Opi ohjelmoimaan oma puhuva robottisi!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 20.09.2018
steps:
  - 
    title: Esittely
  - 
    title: Sinun chatbot
  - 
    title: Puhuva chatbot
  - 
    title: "Haaste: lisää kysymyksiä"
    challenge: true
  - 
    title: Päätösten tekeminen
  - 
    title: "Haaste: enemmän päätöksiä"
    challenge: true
  - 
    title: Sijainnin muuttaminen
  - 
    title: "Haaste: lopeta chatbot"
    challenge: true
  - 
    title: Mitä seuraavaksi?
