---
title: Chatbot
hero_image: images/chatbot.png
description: '¡Aprende a programar tu propio robot que habla!'
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Tu chatbot
  - 
    title: "Un chatbot parlanchín"
    challenge: true
  - 
    title: Tomando decisiones
  - 
    title: "Cambio de posición"
    challenge: true
  - 
    title: 'Desafío: termina tu chatbot'
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
