---
title: Chatbot
hero_image: images/chatbot.png
description: '¡Aprende a programar tu propio robot que habla!'
original_url: https://codeclubprojects.org/en-GB/scratch/chatbot?redirect=false
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: ''
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Tu chatbot
  - 
    title: Un chatbot hablante
  - 
    title: Tomando decisiones
  - 
    title: Cambio de ubicación
  - 
    title: 'Desafío: finaliza tu chatbot'
