---
title: SgwrsBot
hero_image: images/chatbot.png
description: Dysga sut i raglenni robot sydd yn siarad!
theme: fioled
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Cyflwyniad
  - 
    title: Dy SgwrsBot
  - 
    title: SgwrsBot sy'n siarad
  - 
    title: "Her: mwy o gwestiynau"
    challenge: true
  - 
    title: Gwneud penderfyniadau
  - 
    title: "Her: mwy o benderfyniadau"
    challenge: true
  - 
    title: Newid lleoliad
  - 
    title: "Her: cwblhau dy sgwrsbot"
    challenge: true
  - 
    title: Beth nesaf?
