---
title: SgwrsBot
hero_image: images/chatbot.png
description: Dysga sut i raglenni robot sydd yn siarad!
theme: fioled
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Dy SgwrsBot
    completion:
      - engaged
  - 
    title: SgwrsBot sy'n siarad
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
