---
title: Chatbot
hero_image: images/chatbot.png
description: Lerne, Deinen eigenen sprechenden Roboter zu programmieren!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Dein Chatbot
  - 
    title: "Ein sprechender Chatbot"
    challenge: true
  - 
    title: Entscheidungen treffen
  - 
    title: "Ortswechsel"
    challenge: true
  - 
    title: 'Herausforderung: Vervollständige deinen Chatbot'
  - 
    title: "Herausforderung: Vervollständige deinen Chatbot"
    challenge: true
  - 
    title: 'Herausforderung: Ändere das Kostüm deiner Trommel'
