---
title: Chatbot
hero_image: images/chatbot.png
description: Lerne, Deinen eigenen sprechenden Roboter zu programmieren!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Dein Chatbot
    completion:
      - engaged
  - 
    title: Ein sprechender Chatbot
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
