---
title: Chatbot
hero_image: images/chatbot.png
description: Lerne, Deinen eigenen sprechenden Roboter zu programmieren!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Dein Chatbot
  - 
    title: Ein sprechender Chatbot
  - 
    title: "Herausforderung: zusätzliche Fragen"
    challenge: true
  - 
    title: Entscheidungen treffen
  - 
    title: "Herausforderung: zusätzliche Entscheidungen"
    challenge: true
  - 
    title: Ortswechsel
  - 
    title: "Herausforderung: Vervollständige deinen Chatbot"
    challenge: true
  - 
    title: 'Herausforderung: Ändere das Kostüm deiner Trommel'
