---
title: Chatbot
hero_image: images/chatbot.png
description: Learn how to program your own talking robot!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introducere
  - 
    title: Robotul tău vorbitor
  - 
    title: Un robot vorbitor
    completion:
      - engaged
  - 
    title: 'Provocare: mai multe întrebări'
    challenge: true
  - 
    title: Making decisions
  - 
    title: 'Provocare: mai multe decizii'
    challenge: true
  - 
    title: Schimbarea locației
    completion:
      - internal
  - 
    title: 'Provocare: finalizează-ți robotul vorbitor'
    challenge: true
  - 
    title: What next?
