---
title: Robot vorbitor
hero_image: images/chatbot.png
description: Învață cum să îți programezi propriul robot vorbitor!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introducere
  - 
    title: Robotul tău vorbitor
  - 
    title: Un robot vorbitor
  - 
    title: "Provocare: mai multe întrebări"
    challenge: true
  - 
    title: Luarea deciziilor
  - 
    title: "Provocare: mai multe decizii"
    challenge: true
  - 
    title: Schimbarea locației
  - 
    title: "Provocare: finalizează-ți robotul vorbitor"
    challenge: true
  - 
    title: What next?
