---
title: Chatbot
hero_image: images/chatbot.png
description: Acum vom învăța cum să programăm propriul nostru robot vorbitor!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Chatbot
  - 
    title: Chatbot-ul tău
  - 
    title: Un chatbot vorbitor
  - 
    title: "Provocarea: alte întrebări"
    challenge: true
  - 
    title: Making decisions
  - 
    title: "Provocare: alte decizii"
    challenge: true
  - 
    title: Schimbarea poziției
  - 
    title: "Provocare: terminați chatbot-ul"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
