---
title: ChatBot
hero_image: images/chatbot.png
description: Aprenda a programar o seu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Seu chatbot
    completion:
      - engaged
  - 
    title: Um chatbot falante
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
