---
title: ChatBot
hero_image: images/chatbot.png
description: Aprenda a programar o seu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introdução
  - 
    title: Seu chatbot
  - 
    title: Um chatbot falante
    completion:
      - engaged
  - 
    title: 'Desafio: mais perguntas'
    challenge: true
  - 
    title: Tomando decisões
  - 
    title: 'Desafio: mais decisões'
    challenge: true
  - 
    title: Mudando de lugar
    completion:
      - internal
  - 
    title: 'Desafio: Termine o seu ChatBot'
    challenge: true
  - 
    title: E agora?
