---
title: ChatBot
hero_image: images/chatbot.png
description: Aprenda a programar o seu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Seu ChatBot
  - 
    title: "Um ChatBot falante"
    challenge: true
  - 
    title: Tomando decisões
  - 
    title: "Mudando de lugar"
    challenge: true
  - 
    title: 'Desafio: Termine o seu ChatBot'
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
