---
title: ChatBot
hero_image: images/chatbot.png
description: Aprenda a programar o seu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Seu chatbot
  - 
    title: Um chatbot falante
  - 
    title: "Desafio: mais perguntas"
    challenge: true
  - 
    title: Tomando decisões
  - 
    title: "Desafio: mais decisões"
    challenge: true
  - 
    title: Mudando de lugar
  - 
    title: "Desafio: Termine o seu ChatBot"
    challenge: true
  - 
    title: Teste-se
  - 
    title: E agora?
