---
title: ChatBot
hero_image: images/chatbot.png
description: Aprenda a programar o seu próprio robô falante!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introdução
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Tomando decisões
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Desafio: Termine o seu ChatBot"
    challenge: true
  - 
    title: What next?
