---
title: Chatbot
hero_image: images/chatbot.png
description: Pelajari cara memrogram robot bicara anda sendiri!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Pendahuluan
  - 
    title: Chatbot Anda
  - 
    title: Chatbot yang bisa bicara
  - 
    title: "Tantangan: pertanyaan berikutnya"
    challenge: true
  - 
    title: Membuat keputusan
  - 
    title: "Tantangan: keputusan berikutnya"
    challenge: true
  - 
    title: Mengubah lokasi
  - 
    title: "Tantangan: selesaikan chatbot Anda"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
