---
title: Chatbot
hero_image: images/chatbot.png
description: Belajar cara memprogram robot berbicara milik sendiri!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Pengantar
  - 
    title: Chatbot Anda
  - 
    title: Chatbot yang bisa bicara
  - 
    title: "Tantangan: lebih banyak pertanyaan"
    challenge: true
  - 
    title: Membuat keputusan
  - 
    title: "Tantangan: lebih banyak keputusan"
    challenge: true
  - 
    title: Mengubah lokasi
  - 
    title: "Tantangan: selesaikan chatbot Anda"
    challenge: true
  - 
    title: Apa selanjutnya?
