---
title: Xatbot
hero_image: images/chatbot.png
description: Aprèn a programar el teu propi robot parlant!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introducció
  - 
    title: El teu xatbot
  - 
    title: Un xatbot parlant
  - 
    title: "Repte: més preguntes"
    challenge: true
  - 
    title: Prenent decisions
  - 
    title: "Repte: més decisions"
    challenge: true
  - 
    title: Canviant la ubicació
  - 
    title: "Repte: acaba el teu xatbot"
    challenge: true
  - 
    title: I ara què ve?
