---
title: Xatbot
hero_image: images/chatbot.png
description: Aprèn a programar el teu propi robot parlant!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: El teu xatbot
    completion:
      - engaged
  - 
    title: Un xatbot parlant
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
