---
title: Chatbot
hero_image: images / chatbot.png
description: Aprèn a programar el teu propi robot parlant!
theme: violeta
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introducció
  - 
    title: El vostre xat bot
  - 
    title: Un xat bot parlant
  - 
    title: "Repte: més preguntes"
    challenge: true
  - 
    title: Prenent decisions
  - 
    title: "Repte: més decisions"
    challenge: true
  - 
    title: S'està canviant la ubicació
  - 
    title: "Repte: acaba el teu xat bot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
