---
title: Chatbot
hero_image: slike / chatbot.png
description: Preberite, kako programirati svoj lasten govorni robot!
theme: vijolična
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Uvod
  - 
    title: Vaš klepet
  - 
    title: Pogovorni klepet
  - 
    title: "Izziv: več vprašanj"
    challenge: true
  - 
    title: Odločanje
  - 
    title: "Izziv: več odločitev"
    challenge: true
  - 
    title: Spreminjanje lokacije
  - 
    title: "Izziv: dokončajte svoj chatbot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
