---
title: Klepetalni robot
hero_image: slike / chatbot.png
description: Nauči se programirati svoj lastni govoreči robot!
theme: vijolična
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Uvod
  - 
    title: Tvoj klepetalni robot
  - 
    title: Govoreči klepetalni robot
  - 
    title: "Izziv: več vprašanj"
    challenge: true
  - 
    title: Sprejemanje odločitev
  - 
    title: "Izziv: več odločitev"
    challenge: true
  - 
    title: Spreminjanje lokacije
  - 
    title: "Izziv: dokončaj svoj klepetalni robot"
    challenge: true
  - 
    title: Preizkusi se
  - 
    title: Kaj sledi?
