---
title: Povídací robot
hero_image: images/chatbot.png
description: V této lekci se naučíš, jak naprogramovat mluvícího robota!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Úvod
  - 
    title: Váš chatbot
  - 
    title: Mluvící chatbot
  - 
    title: "Výzva: více otázek"
    challenge: true
  - 
    title: Rozhodování
  - 
    title: "Výzva: více rozhodnutí"
    challenge: true
  - 
    title: Změna polohy
  - 
    title: "Výzva: dokončete svůj chatbot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
