---
title: צ’אט בוט (רובוט שיחה)
hero_image: images/chatbot.png
description: אתה הולך ללמוד איך לתכנת צ’אט בוט (רובוט שיחה) לגמרי שלך!
theme: סגול
listed: true
copyedit: false
version: 4.2.0
last_tested: 20-09-2018
steps:
  - 
    title: What you will make
  - 
    title: הצ'אטבוט שלכם
    completion:
      - engaged
  - 
    title: צ'אטבוט מדבר
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
