---
title: צ’אט בוט (רובוט שיחה)
hero_image: images/chatbot.png
description: אתה הולך ללמוד איך לתכנת צ’אט בוט (רובוט שיחה) לגמרי שלך!
theme: סגול
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: צ’אט בוט (רובוט שיחה)
  - 
    title: הצ'אטבוט שלכם
  - 
    title: צ'אטבוט מדבר
  - 
    title: "אתגר: שאלות נוספות"
    challenge: true
  - 
    title: קבלת החלטות
  - 
    title: "אתגר: יותר החלטות"
    challenge: true
  - 
    title: שינוי מיקום
  - 
    title: "אתגר: סיים את הצ'אטבוט שלך"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
