---
title: צ’אט בוט (רובוט שיחה)
hero_image: images/chatbot.png
description: אתה הולך ללמוד איך לתכנת צ’אט בוט (רובוט שיחה) לגמרי שלך!
theme: סגול
listed: true
copyedit: false
version: 4.2.0
last_tested: 20-09-2018
steps:
  - 
    title: הקדמה
  - 
    title: הצ'אטבוט שלכם
  - 
    title: צ'אטבוט מדבר
  - 
    title: "אתגר: שאלות נוספות"
    challenge: true
  - 
    title: קבלת החלטות
  - 
    title: "אתגר: החלטות נוספות"
    challenge: true
  - 
    title: שינוי מיקום
  - 
    title: "אתגר: סיים את הצ'אטבוט שלך"
    challenge: true
  - 
    title: מה הלאה?
