---
title: Chatbot
hero_image: images/chatbot.png
description: Tanuld meg, hogyan programozhatsz saját beszélő robotot!
theme: ibolya
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018.09.20
steps:
  - 
    title: Bevezetés
  - 
    title: A chatbotod
  - 
    title: Beszélő chatbot
  - 
    title: "Kihívás: még több kérdés"
    challenge: true
  - 
    title: Döntéshozatal
  - 
    title: "Kihívás: még több döntés"
    challenge: true
  - 
    title: Hely megváltoztatása
  - 
    title: "Kihívás: fejezd be a chatbotodat"
    challenge: true
  - 
    title: Mi a következő lépés?
