---
title: Chatbot
hero_image: images / chatbot.png
description: Ismerje meg, hogyan programozhatja saját beszélő robotját!
theme: ibolya
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018/09/20
steps:
  - 
    title: Bevezetés
  - 
    title: Az Ön chatbotja
  - 
    title: Beszélő chatbot
  - 
    title: "Kihívás: több kérdés"
    challenge: true
  - 
    title: Döntéshozatal
  - 
    title: "Kihívás: több döntés"
    challenge: true
  - 
    title: Hely megváltoztatása
  - 
    title: "Kihívás: fejezd be a chatbotodat"
    challenge: true
  - 
    title: What next?
