---
title: ಚಾಟ್‌ಬಾಟ್
hero_image: images/chatbot.png
description: ನಿಮ್ಮ ಸ್ವಂತ ಮಾತನಾಡುವ ರೋಬೋಟ್ ಅನ್ನು ಹೇಗೆ ಪ್ರೋಗ್ರಾಂ ಮಾಡುವುದು ಎಂದು ತಿಳಿಯಿರಿ!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: ಪರಿಚಯ
  - 
    title: ನಿಮ್ಮ ಚಾಟ್‌ಬಾಟ್
  - 
    title: ಮಾತನಾಡುವ ಚಾಟ್‌ಬಾಟ್
  - 
    title: "ಸವಾಲು: ಹೆಚ್ಚಿನ ಪ್ರಶ್ನೆಗಳು"
    challenge: true
  - 
    title: ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುವುದು
  - 
    title: "ಸವಾಲು: ಹೆಚ್ಚಿನ ನಿರ್ಧಾರಗಳು"
    challenge: true
  - 
    title: ಸ್ಥಳವನ್ನು ಬದಲಾಯಿಸುವುದು
  - 
    title: "ಸವಾಲು: ನಿಮ್ಮ ಚಾಟ್‌ಬಾಟ್ ಅನ್ನು ಮುಗಿಸಿ"
    challenge: true
  - 
    title: ಮುಂದೆ ಏನು?
