---
title: Robot parlanchín
hero_image: images/chatbot.png
description: '¡Vas a aprender cómo programar tu propio robot que habla!'
theme: violeta
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introducción
  - 
    title: Tu chatbot
  - 
    title: Un chatbot que habla
  - 
    title: "Desafío: más preguntas"
    challenge: true
  - 
    title: Tomando decisiones
  - 
    title: "Desafío: más decisiones"
    challenge: true
  - 
    title: Cambiando ubicación
  - 
    title: "Desafío: termina tu chatbot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
