---
title: 챗봇
hero_image: images/chatbot.png
description: 자신만의 말하는 로봇을 프로그래밍 하는 방법에 대해 배워보세요!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-09-20
steps:
- title: 들어가며
  completion: engaged
- title: 당신의 챗봇
- title: 말하는 챗봇
- title: '도전과제: 더 많은 질문들'
  challenge: true
- title: 결정하기
- title: '도전과제: 더 많은 결정들'
  challenge: true
  completion: internal
- title: 장소 바꾸기
- title: '도전 과제: 챗봇 완성하기'
  challenge: true
- title: 도전해 보기
- title: 더 나아가기
