---
title: Chatbot
hero_image: images / chatbot.png
description: Lugege, kuidas oma räägirobot programmeerida!
theme: violetne
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Sissejuhatus
  - 
    title: Sinu jututuba
  - 
    title: Räägib jututuba
  - 
    title: "Väljakutse: rohkem küsimusi"
    challenge: true
  - 
    title: Otsuste tegemine
  - 
    title: "Väljakutse: rohkem otsuseid"
    challenge: true
  - 
    title: Asukoha muutmine
  - 
    title: "Väljakutse: lõpetage oma jututuba"
    challenge: true
  - 
    title: Mis edasi?
