---
title: Robot gaduła
hero_image: images/chatbot.png
description: Naucz się jak programować własnego mówiącego robota!
theme: fioletowy
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Wprowadzenie
  - 
    title: Twój robot gaduła
  - 
    title: Rozmawiający robot
  - 
    title: "Wyzwanie: więcej pytań"
    challenge: true
  - 
    title: Podejmowanie decyzji
  - 
    title: "Wyzwanie: więcej decyzji"
    challenge: true
  - 
    title: Zmiana lokalizacji
  - 
    title: "Wyzwanie: ukończ swojego robota"
    challenge: true
  - 
    title: Sprawdź się
  - 
    title: Co dalej?
