---
title: Robot gaduła
hero_image: images/chatbot.png
description: Naucz się jak programować własnego mówiącego robota!
theme: fioletowy
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Twój robot gaduła
    completion:
      - engaged
  - 
    title: Gadający robot
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
