---
title: Robot gaduła
hero_image: images/chatbot.png
description: Naucz się jak programować własnego mówiącego robota!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Podejmowanie decyzji
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
