---
title: Hovoriaci robot
hero_image: images/chatbot.png
description: V tomto projekte sa naučíš ako naprogramovať svojho vlastného hovoriaceho robota!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Hovoriaci robot
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Making decisions
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
