---
title: Hovoriaci robot
hero_image: images/chatbot.png
description: V tomto projekte sa naučíš ako naprogramovať svojho vlastného hovoriaceho robota!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Úvod
  - 
    title: Tvoj hovoriaci robot
  - 
    title: Hovoriaci robot
  - 
    title: "Výzva: viac otázok"
    challenge: true
  - 
    title: Rozhodovanie
  - 
    title: "Výzva: viac rozhodnutí"
    challenge: true
  - 
    title: Zmena miesta
  - 
    title: "Výzva: dokonči svojho hovoriaceho robota"
    challenge: true
  - 
    title: Čo ďalej?
