---
title: Chatbot
hero_image: imej / chatbot.png
description: Ketahui bagaimana untuk memprogram robot bercakap anda sendiri!
theme: ungu
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Pengenalan
  - 
    title: Your chatbot
  - 
    title: A talking chatbot
  - 
    title: "Challenge: more questions"
    challenge: true
  - 
    title: Membuat keputusan
  - 
    title: "Challenge: more decisions"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
