---
title: Robot koji razgovara
hero_image: images/chatbot.png
description: Nauči kako da programiraš sopstvenog robota koji govori!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Tvoj robot koji razgovara
  - 
    title: "Pričljivi robot"
    challenge: true
  - 
    title: Donošenje odluka
  - 
    title: "Promjena lokacije"
    challenge: true
  - 
    title: 'Izazov: dovrši svog robota'
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
