---
title: Robot parlant
hero_image: images/chatbot.png
description: Apprends à programmer ton propre robot qui parle!
theme: violet
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Votre robot parlant
  - 
    title: Un chatbot parlant
  - 
    title: "Prendre des décisions"
    challenge: true
  - 
    title: Changement d'emplacement
  - 
    title: "Défi : Créer votre propre chatbot"
    challenge: true
  - 
    title: Changing location
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
