---
title: Robot parlant
hero_image: images/chatbot.png
description: Apprends à programmer ton propre robot qui parle!
theme: violet
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Un chatbot parlant
  - 
    title: Prendre des décisions
  - 
    title: "Challenge : plus d'objets"
    challenge: true
  - 
    title: Changement d'emplacement
  - 
    title: "Challenge : plus d'objets"
    challenge: true
  - 
    title: 'Défi : Créer votre propre chatbot'
  - 
    title: "Défi: terminez votre chatbot"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
