---
title: Chatbot
hero_image: images/chatbot.png
description: Apprends à programmer ton propre robot qui parle!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Introduction
  - 
    title: Ton chatbot
  - 
    title: Un chatbot parlant
  - 
    title: "Challenge : plus de questions"
    challenge: true
  - 
    title: Prendre des décisions
  - 
    title: "Challenge : plus de décisions"
    challenge: true
  - 
    title: Changer d'emplacement
  - 
    title: "Défi: termine ton chatbot"
    challenge: true
  - 
    title: Teste-toi
