---
title: ChiacchieRobot
hero_image: images/chatbot.png
description: Impara a programmare il tuo robot parlante!
theme: violet
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: What you will make
  - 
    title: Il tuo ChiacchieRobot
    completion:
      - engaged
  - 
    title: Il tuo ChiacchieRobot
    completion:
      - internal
  - 
    title: Making decisions
  - 
    title: Changing location
    completion:
      - external
  - 
    title: Challenge
    challenge: true
