---
title: ChiacchieRobot
hero_image: images/chatbot.png
description: Impara a programmare il tuo robot parlante!
theme: violet
listed: true
copyedit: false
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Il tuo ChiacchieRobot
  - 
    title: "Un ChiacchieRobot parlante"
    challenge: true
  - 
    title: Prendere decisioni
  - 
    title: "Cambiare posizione"
    challenge: true
  - 
    title: 'Sfida: Completa il tuo ChiacchieRobot'
  - 
    title: "Challenge: finish your chatbot"
    challenge: true
  - 
    title: What next?
