---
title: chatbot
hero_image: images / chatbot.png
description: Kendi konuşan robotunuzu nasıl programlayacağınızı öğrenin!
theme: menekşe
listed: true
copyedit: false
version: 4.2.0
last_tested: 2018-09-20
steps:
  - 
    title: Giriş
  - 
    title: Senin chatbot
  - 
    title: Konuşan bir chatbot
  - 
    title: "Zorluk: daha fazla soru"
    challenge: true
  - 
    title: Karar vermek
  - 
    title: "Zorluk: daha fazla karar"
    challenge: true
  - 
    title: Konum değiştirme
  - 
    title: "Zorluk: sohbetinizi bitirin"
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
